import type { Metadata } from "next";
import { loadContent } from "~/lib/content";
import { Hero } from "~/components/sections/Hero";
import { WhatMatters } from "~/components/sections/WhatMatters";
import { ConceptMap } from "~/components/sections/ConceptMap";
import { KeyIdeas } from "~/components/sections/KeyIdeas";
import { Timeline } from "~/components/sections/Timeline";
import { Comparison } from "~/components/sections/Comparison";
import { ExamplesAndAnalogies } from "~/components/sections/ExamplesAndAnalogies";
import { Misconceptions } from "~/components/sections/Misconceptions";
import { Glossary } from "~/components/sections/Glossary";
import { Takeaways } from "~/components/sections/Takeaways";
import { Sources } from "~/components/sections/Sources";
import { FixtureBanner } from "~/components/ui/FixtureBanner";
import { ProgressRail } from "~/components/ui/ProgressRail";

export const dynamic = "force-static";
export const revalidate = false;

export async function generateMetadata(): Promise<Metadata> {
  const c = loadContent();
  return {
    title: c.topic,
    description: c.oneSentenceAnswer,
    openGraph: {
      title: `${c.topic} — Recap Studio`,
      description: c.oneSentenceAnswer,
    },
  };
}

export default function Page() {
  const content = loadContent();
  const enabled = new Set(
    content.visualSections.filter((s) => s.enabled).map((s) => s.kind),
  );

  return (
    <>
      <ProgressRail sections={content.visualSections.filter((s) => s.enabled).map((s) => s.kind)} />
      <main className="mx-auto w-full max-w-3xl px-5 pb-24 pt-10 md:max-w-4xl md:px-8 md:pt-16">
        {content.fixture ? <FixtureBanner /> : null}

        {enabled.has("hero") ? <Hero content={content} /> : null}
        {enabled.has("matters") ? <WhatMatters content={content} /> : null}
        {enabled.has("concept-map") ? <ConceptMap content={content} /> : null}
        {enabled.has("ideas") ? <KeyIdeas content={content} /> : null}
        {enabled.has("timeline") && content.timeline?.length ? (
          <Timeline content={content} />
        ) : null}
        {enabled.has("comparison") && content.comparisons?.length ? (
          <Comparison content={content} />
        ) : null}
        {enabled.has("examples") || enabled.has("analogies") ? (
          <ExamplesAndAnalogies content={content} />
        ) : null}
        {enabled.has("misconceptions") ? <Misconceptions content={content} /> : null}
        {enabled.has("glossary") ? <Glossary content={content} /> : null}
        {enabled.has("takeaways") ? <Takeaways content={content} /> : null}
        {enabled.has("sources") ? <Sources content={content} /> : null}
      </main>
      <footer className="border-t border-line/60 py-10 text-center text-sm text-muted dark:border-line-dark dark:text-muted-dark">
        <p>Generated by <strong>Recap Studio</strong>. Be skeptical, run your own evals.</p>
      </footer>
    </>
  );
}
