/**
 * @recap-studio/html-renderer
 *
 * Render a typed RecapPageContent into ONE self-contained, dark-mode,
 * mobile-first HTML document. No framework, no build step, no runtime JS, no
 * external requests. The output opens with a double-click and works offline.
 *
 * This is the reusable visual template behind Recap Studio. Any tool that can
 * produce a RecapPageContent (or the equivalent JSON) can call renderToHtml()
 * and get a shareable page. See TEMPLATE.md for the reuse + white-label guide.
 */
import {
  parseRecapPageContent,
  type RecapPageContent,
} from "@recap-studio/content-pipeline";
import { composeBody, readingMinutes } from "./sections.js";
import { documentShell, type ShellOptions } from "./shell.js";
import { getBaseStyles, type Theme, type CssOptions } from "./css.js";

export interface RenderOptions {
  /** dark | light | auto. Default "dark" (the Recap Studio house style). */
  theme?: Theme;
  /** Reveal animation intensity. Default "low". Always reduced-motion safe. */
  animation?: "none" | "low" | "medium" | "high";
  /** <html lang>. Default "en". */
  lang?: string;
  /** Footer attribution line. Default "Generated by Recap Studio". */
  attribution?: string;
  /**
   * Render for paper: the print rules apply on screen as well, and the
   * document is painted light. Without this, the page keeps its screen theme
   * and the same rules still apply when the reader actually prints.
   */
  print?: boolean;
}

/**
 * Render validated content to a complete HTML document string.
 * Throws nothing for valid content; assumes the input already matches the
 * RecapPageContent shape (use renderFromJson to parse + validate first).
 */
export function renderToHtml(
  content: RecapPageContent,
  options: RenderOptions = {},
): string {
  const body = composeBody(content, { print: options.print === true });
  return documentShell(content, body, options as ShellOptions);
}

/**
 * Parse + validate an unknown JSON value, then render. Throws a descriptive
 * error if the content does not match the schema. This is the entry point the
 * CLI and MCP server use.
 */
export function renderFromJson(
  json: unknown,
  options: RenderOptions = {},
): string {
  const content = parseRecapPageContent(json);
  return renderToHtml(content, options);
}

export { getBaseStyles, readingMinutes };
export type { Theme, CssOptions, RecapPageContent };
