/**
 * The HTML document shell: <!DOCTYPE>, <head> meta, the inlined <style>, skip
 * link, and footer. No external resources, no <script>. Opens via file://.
 */
import type { RecapPageContent } from "@recap-studio/content-pipeline";
import { esc, escAttr } from "./escape.js";
import { getBaseStyles, type Theme } from "./css.js";

export interface ShellOptions {
  theme?: Theme;
  animation?: "none" | "low" | "medium" | "high";
  lang?: string;
  attribution?: string;
}

// A tiny inline SVG favicon (violet "R" mark) as a data URI — keeps the file
// self-contained and avoids a 404 for /favicon.ico under file://.
const FAVICON =
  "data:image/svg+xml," +
  encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="7" fill="#0B0B0F"/><text x="16" y="22" font-family="Georgia,serif" font-size="18" fill="#8B6DFF" text-anchor="middle">R</text></svg>',
  );

export function documentShell(c: RecapPageContent, body: string, opts: ShellOptions = {}): string {
  const theme = opts.theme ?? "dark";
  const lang = opts.lang ?? "en";
  const attribution = opts.attribution ?? "Generated by Recap Studio";
  const css = getBaseStyles({ theme, animation: opts.animation ?? "low" });
  const themeAttr = theme === "auto" ? "" : ` data-theme="${theme}"`;
  const desc = String(c.oneSentenceAnswer ?? "").slice(0, 200);
  const fixtureBanner = c.fixture
    ? `<div class="recap-fixture" role="note"><svg class="recap-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><path d="M12 9v4"/><path d="M12 17h.01"/></svg> Demo content from a fixture — not a live research run.</div>`
    : "";

  return `<!doctype html>
<html lang="${escAttr(lang)}"${themeAttr}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="color-scheme" content="${theme === "auto" ? "dark light" : theme}">
<meta name="theme-color" content="#0B0B0F">
<meta name="generator" content="Recap Studio">
<title>${esc(c.topic)}</title>
<meta name="description" content="${escAttr(desc)}">
<meta property="og:title" content="${escAttr(c.topic)}">
<meta property="og:description" content="${escAttr(desc)}">
<meta property="og:type" content="article">
<link rel="icon" href="${FAVICON}">
<style>${css}</style>
</head>
<body>
<a class="recap-skip" href="#hero">Skip to summary</a>
<main class="recap-main" id="top">
${fixtureBanner}
${body}
</main>
<footer class="recap-footer">
<p><strong>${esc(attribution)}.</strong> One page, offline, yours. Be skeptical — check the sources.</p>
</footer>
</body>
</html>
`;
}
