/**
 * RecapStudioConfig — typed user-tunable knobs. Safe defaults make every
 * side effect opt-in.
 */
import { z } from "zod";

export const RecapStudioConfig = z.object({
  contentLength: z.enum(["short", "medium", "long"]).default("medium"),
  explanationDepth: z
    .enum(["beginner", "intermediate", "expert"])
    .default("beginner"),
  researchIntensity: z.enum(["fast", "balanced", "deep"]).default("balanced"),
  theme: z.enum(["light", "dark", "auto"]).default("auto"),
  animationIntensity: z
    .enum(["none", "low", "medium", "high"])
    .default("low"),
  visualDensity: z.enum(["low", "medium", "high"]).default("medium"),
  deploymentMode: z
    .enum(["disabled", "preview", "production-with-confirmation"])
    .default("disabled"),
  emailMode: z
    .enum(["disabled", "draft", "send-with-confirmation"])
    .default("disabled"),
  citationStrictness: z
    .enum(["standard", "strict", "academic"])
    .default("strict"),
  costMode: z.enum(["economy", "balanced", "premium"]).default("balanced"),
  modelRouting: z.enum(["auto", "manual"]).default("auto"),
  sourceFreshnessRequired: z.boolean().default(true),
  /** v0.2: gates rendering or deploys behind a human checklist. */
  humanReviewMode: z
    .enum(["off", "before-publish", "before-deploy"])
    .default("off"),
  /** v0.2: default locale for generated UI chrome. Content language is decided per-run. */
  defaultLocale: z.enum(["en", "fr", "es", "de", "pt", "ja"]).default("en"),
  /** v0.2: opt in to local-only reader counters. No third-party telemetry. */
  analyticsMode: z.enum(["off", "local-only"]).default("off"),
});
export type RecapStudioConfig = z.infer<typeof RecapStudioConfig>;

export const DEFAULT_CONFIG: RecapStudioConfig = RecapStudioConfig.parse({});

/**
 * Read config from process env + an optional JSON sidecar.
 * Pure: takes no fs dependency so it ports to edge / browser-safe contexts.
 */
export function resolveConfig(
  overrides: Partial<RecapStudioConfig> = {},
  envSnapshot: Record<string, string | undefined> = process.env,
): RecapStudioConfig {
  const cfg = { ...DEFAULT_CONFIG, ...overrides };

  // Hard override: fixture-only mode forces every side-effect off.
  if (envSnapshot.RECAP_STUDIO_FIXTURE_ONLY === "1") {
    cfg.researchIntensity = "fast";
    cfg.deploymentMode = "disabled";
    cfg.emailMode = "disabled";
    cfg.costMode = "economy";
  }

  return RecapStudioConfig.parse(cfg);
}

/**
 * Stringify the config to a `recap-studio.config.ts` source file.
 */
export function renderConfigSource(cfg: RecapStudioConfig): string {
  const body = JSON.stringify(cfg, null, 2);
  return [
    "// Auto-generated by /recap setup. Edit by hand to tune Recap Studio.",
    "// Side effects (deploy, email, paid APIs) are off by default — opt in here.",
    "",
    'import type { RecapStudioConfig } from "@recap-studio/content-pipeline";',
    "",
    `export const config: RecapStudioConfig = ${body};`,
    "",
    "export default config;",
    "",
  ].join("\n");
}
