/**
 * Locales — multi-language scaffold.
 *
 * Each locale ships a typed UI string table that the Next.js renderer can
 * consume. Content (RecapPageContent) is generated per-locale by the
 * agents; this module only handles UI chrome.
 */
import { z } from "zod";

export const Locale = z.enum(["en", "fr", "es", "de", "pt", "ja"]);
export type Locale = z.infer<typeof Locale>;

export const UIStrings = z.object({
  skipToSummary: z.string(),
  fixtureNotice: z.string(),
  glossaryToggle: z.string(),
  takeawaysTitle: z.string(),
  sourcesTitle: z.string(),
  uncertaintyTitle: z.string(),
  footerTagline: z.string(),
});
export type UIStrings = z.infer<typeof UIStrings>;

export const STRINGS: Record<Locale, UIStrings> = {
  en: {
    skipToSummary: "Skip to summary",
    fixtureNotice: "Fixture data. Re-run after wiring research keys to see live sources.",
    glossaryToggle: "terms — tap to expand",
    takeawaysTitle: "Things to do today",
    sourcesTitle: "Where this comes from",
    uncertaintyTitle: "Uncertainty notes",
    footerTagline: "Generated by Recap Studio. Be skeptical, run your own evals.",
  },
  fr: {
    skipToSummary: "Aller au résumé",
    fixtureNotice: "Données de démo. Relancez avec des clés de recherche pour voir les sources réelles.",
    glossaryToggle: "termes — appuyer pour développer",
    takeawaysTitle: "À faire aujourd'hui",
    sourcesTitle: "D'où ça vient",
    uncertaintyTitle: "Notes d'incertitude",
    footerTagline: "Généré par Recap Studio. Restez sceptique, faites vos propres tests.",
  },
  es: {
    skipToSummary: "Saltar al resumen",
    fixtureNotice: "Datos de demostración. Vuelve a ejecutar tras configurar las claves para ver fuentes reales.",
    glossaryToggle: "términos — pulsa para ampliar",
    takeawaysTitle: "Qué hacer hoy",
    sourcesTitle: "De dónde sale esto",
    uncertaintyTitle: "Notas de incertidumbre",
    footerTagline: "Generado por Recap Studio. Sé escéptico, haz tus propias pruebas.",
  },
  de: {
    skipToSummary: "Zur Zusammenfassung springen",
    fixtureNotice: "Beispieldaten. Mit Recherche-Keys neu starten für echte Quellen.",
    glossaryToggle: "Begriffe — zum Ausklappen tippen",
    takeawaysTitle: "Heute umsetzen",
    sourcesTitle: "Woher das kommt",
    uncertaintyTitle: "Unsicherheits-Hinweise",
    footerTagline: "Erstellt mit Recap Studio. Bleib skeptisch, prüfe selbst.",
  },
  pt: {
    skipToSummary: "Ir para o resumo",
    fixtureNotice: "Dados de demonstração. Rode novamente com chaves para ver fontes reais.",
    glossaryToggle: "termos — toque para expandir",
    takeawaysTitle: "Para hoje",
    sourcesTitle: "De onde vem isso",
    uncertaintyTitle: "Notas de incerteza",
    footerTagline: "Gerado por Recap Studio. Seja cético, faça seus próprios testes.",
  },
  ja: {
    skipToSummary: "サマリーへ",
    fixtureNotice: "フィクスチャ。リサーチ用キーを設定して再実行すると実ソースを表示します。",
    glossaryToggle: "件 — タップで展開",
    takeawaysTitle: "今日できること",
    sourcesTitle: "出典",
    uncertaintyTitle: "不確かさのメモ",
    footerTagline: "Recap Studio で生成。常に検証を。",
  },
};

export function resolveStrings(locale: string | undefined): UIStrings {
  const parsed = Locale.safeParse(locale ?? "en");
  return STRINGS[parsed.success ? parsed.data : "en"];
}
